export default {
  // Test environment
  testEnvironment: 'node',

  // Enable ES modules support
  transform: {},

  // Coverage configuration
  //
  // Public/dist/* is generated by `npm run build:js` and is gitignored, so it exists
  // locally but never in CI — including it made the coverage percentage differ between
  // environments. It is also a minified duplicate of source already counted here, and
  // accounted for 26% of the denominator. See COVERAGE-POLICY.md.
  collectCoverageFrom: [
    'server/**/*.js',
    'Public/**/*.js',
    '!Public/dist/**',
    '!**/*.min.js',
    '!**/node_modules/**',
    '!**/coverage/**',
    '!**/test/**'
  ],

  coverageDirectory: 'coverage',

  coverageReporters: ['text', 'lcov', 'html', 'json-summary'],

  // Thresholds are per-area, not global. A single global number averaging a ~62%-covered
  // server against a ~3%-covered browser tree describes neither, and dilutes every new
  // server test 3:1 against untested client mass.
  //
  // Jest subtracts path-keyed files from the `global` pool, so `global` below is the
  // server remainder (server/** minus utils.js and generators.js), NOT the whole tree.
  //
  // Every number is set just under its measured actual so CI is honest from day one and
  // can only ratchet upward. Raise on merge when actual exceeds threshold by >=3.
  coverageThreshold: {
    // server remainder — actual 53.6 / 43.9 / 50.9 / 54.9
    global: {
      statements: 51,
      branches: 41,
      functions: 48,
      lines: 52,
    },
    // the Phase 3 refactor target — held high so consolidation cannot quietly lose coverage
    './server/generators.js': {
      statements: 87,
      branches: 75,
      functions: 95,
      lines: 88,
    },
    './server/utils.js': {
      statements: 100,
      branches: 100,
      functions: 100,
      lines: 100,
    },
    // Browser tree — floor only, so it can move in one direction. Raised as the Phase 2
    // characterization tests land, not by writing jsdom tests to satisfy a number.
    './Public/': {
      statements: 2,
      branches: 2,
      functions: 2,
      lines: 2,
    },
  },

  // Test match patterns
  testMatch: [
    '**/tests/**/*.test.js',
    '**/__tests__/**/*.test.js',
    '**/?(*.)+(spec|test).js',
  ],

  // Setup files
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],

  // Ignore patterns
  testPathIgnorePatterns: [
    '/node_modules/',
    '/coverage/',
  ],

  // Module name mapper for ES6
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1'
  },

  // Verbose output
  verbose: true,

  // Test timeout
  testTimeout: 10000,

  // Make Jest globals available in ES modules
  injectGlobals: true,

  // Clear mocks between tests
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
